supermaven-inc/supermaven-nvim

lua/supermaven-nvim/util.lua
This fixes the issue caused by temporary buffers created by plugins like Telescope and Harpoon.
=> fix(util.lua): fix errors due to temporary buffers

lua/supermaven-nvim/binary/binary_handler.lua
Could not use the plugin because vim.uv is missing in neovim v0.9.5.
=> fix: attempt to index field 'uv' (a nil value) on neovim < 0.10

lua/supermaven-nvim/completion_preview.lua, lua/supermaven-nvim/util.lua
The main change is at the end of the `CompletionPreview.on_accept_suggestion()`, I calculate the new cursor position based on the number of lines in the `completion_text`.
So I just:
- Split the the completion_text into lines using vim.split()
- Then update the new cursor position using nvim_win_set_cursor()
Setting the cursor position using `nvim_win_set_cursor()` is a more standard approach, especially if users have certain keybindings for specific keys compared to PR #2.
This fixes Issue #2.
=> fix(completion_preview.lua): fix for cursor position for multi line completions

README.md, lua/supermaven-nvim/cmp.lua, lua/supermaven-nvim/completion_preview.lua, lua/supermaven-nvim/config.lua, lua/supermaven-nvim/init.lua
This pull request adds new nvim-cmp compatibility by registering itself as a source when nvim-cmp is found. This makes the plugin much more usable to me and removes the conflict between inline suggestions and cmp's suggestions. I have seen similar requests passing by a couple of times on Discord as well. Additionally, a new configuration option disable_inline_completion has been introduced to allow users to disable the built-in inline completions when relying on the nvim-cmp ones. I have also updated the README accordingly.
It seemed much nicer and more integrated to have this feature in the main repo. However, with a joint effort, it can be made into a separate plugin as well.
While at it, I also added a helper function ```.has_suggestion()``` to help with alternative implementations. …
=> feature: added nvim-cmp source registration and option to disable built in inline suggestions

lua/supermaven-nvim/binary/binary_fetcher.lua
Solves https://github.com/supermaven-inc/supermaven-nvim/issues/19 by using the list-style invocation of `vim.fn.system`, which does not prefix the result with gabrage bytes for some reason.
For details see [this comment](https://github.com/supermaven-inc/supermaven-nvim/issues/19#issuecomment-2139229521)
=> Pass array instead of raw string

README.md, lua/supermaven-nvim/api.lua, lua/supermaven-nvim/binary/binary_fetcher.lua, lua/supermaven-nvim/binary/binary_handler.lua, lua/supermaven-nvim/cmp.lua, lua/supermaven-nvim/commands.lua, lua/supermaven-nvim/completion_preview.lua, lua/supermaven-nvim/config.lua, lua/supermaven-nvim/document_listener.lua, lua/supermaven-nvim/init.lua, lua/supermaven-nvim/textual.lua, lua/supermaven-nvim/util.lua
Hello! This is a small refactor of the project which improves modularity and the management of resources.
- Makes it possible to stop supermaven-nvim, which kills the binary and removes all of the autocommands (Fixes #36)
- Modularizes the code by introducing `supermaven-nvim.api` and `supermaven-nvim.commands` modules
- Adds `SupermavenStart`, `SupermavenStop`, `SupermavenRestart`, `SupermavenToggle`, and `SupermavenStatus` commands
- Makes `supermaven-nvim.config` the source of truth for the current config, rather than passing a table around from `supermaven-nvim.init`
- Applies stylua formatting
- Removes unused imports
- Updates README to document these changes
Because this touches a lot of lines of code, this probably conflicts with several other open PRs. I'm happy to split this up …
=> Feat: Make supermaven-nvim stoppable and minor refactor to follow best practices

lua/supermaven-nvim/binary/binary_fetcher.lua
Prevents #31 from happening. Currently the plugin does not attempt to download the binary if `sm-agent` exists, even if `sm-agent` is incomplete.
=> Download files to temporary name

lua/supermaven-nvim/binary/binary_handler.lua
`vim.api.nvim_win_set_option` and `vim.api.nvim_buf_set_option` are combined into `vim.api.nvim_set_option_value` from v0.10.0 onwards.
> [!NOTE]
> For `height` and `width` it can be used `vim.o.lines` and `vim.o.columns` if we want to drop the `vim.api.nvim_get_option` or `vim.api.nvim_get_option_value`.
- [Deprecated API changes from v0.10.0 onwards](https://neovim.io/doc/user/deprecated.html#deprecated-0.10)
=> feat: added nvim v0.10.0 deprecated API support

README.md, lua/supermaven-nvim/api.lua, lua/supermaven-nvim/binary/binary_fetcher.lua, lua/supermaven-nvim/binary/binary_handler.lua, lua/supermaven-nvim/commands.lua, lua/supermaven-nvim/config.lua, lua/supermaven-nvim/init.lua, lua/supermaven-nvim/logger.lua, lua/supermaven-nvim/textual.lua, lua/supermaven-nvim/util.lua
- With `silence_info` and `debug` on:
https://github.com/supermaven-inc/supermaven-nvim/assets/71392160/0be8797b-d6fa-4cb2-b6bd-beae5c57539b
- With `silence_info` and `debug` off:
https://github.com/supermaven-inc/supermaven-nvim/assets/71392160/d3300bde-9a8d-420d-9dd3-3a85187f479a
1. Import the logger `local log = require("supermaven-nvim.logger")`.
2. Decide which level of information you want the user to see.
- Levels:
- "error": Always shows.
- "warn": Always shows.
- "info": Always shows. (like `print`)
- "debug": shows if `debug` is true.
- "trace": shows if `silence_info` is true.
- "off": logger turned off completely `log_level` option is set too `"off"`.
3. If you have them set to `debug = true` or/and silenced info, `:SupermavenShowLog` to show the log file with timestamps and …
=> feat(#18): add `silence_info` and created `logger` to write to a log file

lua/supermaven-nvim/logger.lua
If `log_level` is set to anything other than `"warn"` or `"error"`, print information if is not unset with `"off"`.
This lets users have better control if the want all kinds of information, like `Starting Supermaven ...` or just the warns and errors.
Fixes #70.
=> fix(logger): improve `log_level` control

lua/supermaven-nvim/binary/binary_handler.lua
When testing out the issue in #12 I found that the files in `ignore_filetypes` were not being ignored properly causing it to still process them. In my case I ignored `.lua` and `.md` filetypes and still was giving me suggestions.
After this fix, it no longer gives me suggestions and it prevents supermaven from starting in ignored files but works fine when changing to a non-ingored filetype.
For the video I used this configuration:
```lua
require("supermaven-nvim").setup({
ignore_filetypes = {
"lua",
},
})
```
https://github.com/supermaven-inc/supermaven-nvim/assets/71392160/a3ff66c4-a372-4995-8112-a340b8b69352
> [!NOTE]
> In the video I forgot to show that going from the non-ignored `.md` to an ingored `.lua` stops showing suggestions or 'polling' or updating until you change to a …
=> fix(#12): ensure ignoring filetypes properly

README.md, lua/supermaven-nvim/binary/binary_handler.lua, lua/supermaven-nvim/config.lua, lua/supermaven-nvim/document_listener.lua
With these changes the user can stop `supermaven` conditionally for example, if the user wants files like `bash_private.sh` to not be running but want any other `.sh` files to have `supermaven` running it can do it with the following configuration.
```lua
require("supermaven-nvim").setup({
condition = function()
return string.match(vim.fn.expand(":t"), "_private.sh")
end,
})
```
---
For this demo I used:
```lua
require("supermaven-nvim").setup({
condition = function()
return vim.fn.expand(":t:r") == "api"
end,
})
```
https://github.com/supermaven-inc/supermaven-nvim/assets/71392160/a1efb698-8e5b-49a2-af39-d2b5887fc492
> [!NOTE]
> It runs on `lua` files except in `api.lua` because the filename is `api`.
Closes #57.
=> feat(#57): disable `supermaven-nvim` on condition

README.md, lua/supermaven-nvim/binary/binary_handler.lua
Allows `ignore_filetypes` to take in an array of strings rather than key-value pairs
=> Support array for ignore_filetype

lua/supermaven-nvim/completion_preview.lua
Problem: When the current line contains specific non-ASCII characters, there's an `index out of range` error.
Cause: The `offset_encoding` is set to `utf-16` while the applied range uses `utf-8` compatible indexing.
Solution: use `utf-8` for `offset_encoding`
=> fix: use correct offset_encoding

lua/supermaven-nvim/logger.lua
This PR controls the corner case mentioned in the linked issue, creating `~/.cache/nvim` if doesn't exist.
Fixes #65
=> fix(#65): create `~/.cache/nvim` if doesn't exist

lua/supermaven-nvim/api.lua, lua/supermaven-nvim/binary/binary_fetcher.lua, lua/supermaven-nvim/binary/binary_handler.lua, lua/supermaven-nvim/cmp.lua, lua/supermaven-nvim/logger.lua, lua/supermaven-nvim/util.lua
@sm-victorw According to the suggestion from @Frestein in #90, I added the `deprecated api` to [`util.lua`](https://github.com/supermaven-inc/supermaven-nvim/blob/main/lua/supermaven-nvim/util.lua) along with disabling `deprecated` warning for lsp use in the file.
With these changes, if we need to use or change some `api` that is deprecated, we can do it inside. `util.lua`
=> feat: add deprecated `api` to `util`

lua/supermaven-nvim/completion_preview.lua, lua/supermaven-nvim/document_listener.lua
There is a bug in Supermaven when using plugins that uses popup menus to display completions, e.g.: [mini.nvim#mini-completion](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-completion.md)
When popup is open, Supermaven seem to completely stop tracking inserted text, and in turn, updating inlay completion:
In this case, I typed `vim.paste` - but inlay completion is not updated with this text.
Furthermore when I accept completion with `<Tab>`:
I get `vim.pasteprint(...)` - which is not at all what completion showed - instead it seems to insert completion on top of what I already entered.
The reason for this behaviour is missing `TextChangedP` event in autocmds: when popup menu is displayed this is the event that will be triggered in Insert mode instead of regular …
=> Fix inlay completions not working correctly when completion popup is open

lua/supermaven-nvim/binary/binary_fetcher.lua
Seems the sm-agent binary still create the ~/.supermaven/config.json, sm-agent will need to be updated upstream
close #37
=> feat(xdg spec): use $XDG_DATA_HOME by default

README.md, lua/supermaven-nvim/cmp.lua
I previously made a PR (accepted) which introduced cmp source integration and a couple of convenience methods. #28 
This pull request contains a minor update to make better use of built in cmp types and multi line markers, cursor, etc. I had added my own marker previously, so it doesn't change much. But I feel it is cleaner this way.
I also tried to simulate the built in continuous inline completions with cmp and came up with a solution which has been working nicely for me for the last couple of days now, so I thought I could share this as a "pro tip" in the README, although this may perhaps be better suited for a wiki in the future.
The new README suggestion is demonstrated in this video:
https://github.com/supermaven-inc/supermaven-nvim/assets/87830/9871857a-56d3-44f9-abfc-b727f01d3565 …
=> feature update: use cmp built in types and cursor; add pro tip to readme

lua/supermaven-nvim/completion_preview.lua
This change is to fix invalid buffer errors while Supermaven is running and using extensions such as telescope and neo-tree.
=> Check for valid buffer in completion_preview.lua
